### ISSUE TITLE
Баги, которые я нашла, нужна помощь в исправлении

### ISSUE THREAD

**Issue by pugprogram** [ynastt/EBNF-to-CFG#6]
Правило вида (ab)(cd), не правильно парсится,
(ab)(cd) 2
ab)(cd 4
a 5
b)(cd 4
b 5
 0
Проверила на других скобках, тоже....
Bruh....

**Comment by pugprogram** [comment]
Не забыть пофиксить 1 грамматику

**Comment by ynastt** [comment]
поправила, теперь есть функция findClosingParanthesis(string str, char pstart, char pend) - ищет индекс закрывающей скобки pend для соответствующей открывающей скобки pstart. Вложенность скобок учитывается

**Comment by ynastt** [comment]
== RULE 0 ==
NTERM: S
RIGHT PART TREE:
{ab}{[cd]}
{ab}
ab
a
b
{[cd]}
[cd]
cd
c
d

пример забыла, вот
